[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
eqsolver = "0.2.0"
itertools = "0.13.0"
nalgebra = "0.33.2"
num-bigint = "0.4.6"
rayon = "1.10.0"
regex = "1.11.1"

[profile.release]
debug = 1
